// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateShortLink(ctx context.Context, arg CreateShortLinkParams) (ShortLink, error)
	DeleteShortLink(ctx context.Context, id int32) (ShortLink, error)
	GetShortLinkById(ctx context.Context, id int32) (ShortLink, error)
	GetShortLinks(ctx context.Context) ([]ShortLink, error)
	UpdateShortLink(ctx context.Context, arg UpdateShortLinkParams) (ShortLink, error)
}

var _ Querier = (*Queries)(nil)
