// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: short_links.sql

package db

import (
	"context"
)

const createShortLink = `-- name: CreateShortLink :one
INSERT INTO
    short_links (original_url, short_name, short_url)
VALUES
    (
        $1,
        $2,
        $3
    ) RETURNING id,
    original_url,
    short_name,
    short_url,
    created_at
`

type CreateShortLinkParams struct {
	OriginalUrl string `json:"original_url"`
	ShortName   string `json:"short_name"`
	ShortUrl    string `json:"short_url"`
}

func (q *Queries) CreateShortLink(ctx context.Context, arg CreateShortLinkParams) (ShortLink, error) {
	row := q.db.QueryRow(ctx, createShortLink, arg.OriginalUrl, arg.ShortName, arg.ShortUrl)
	var i ShortLink
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteShortLink = `-- name: DeleteShortLink :one
DELETE FROM short_links
WHERE
    id = $1 RETURNING id,
    original_url,
    short_name,
    short_url,
    created_at
`

func (q *Queries) DeleteShortLink(ctx context.Context, id int32) (ShortLink, error) {
	row := q.db.QueryRow(ctx, deleteShortLink, id)
	var i ShortLink
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getShortLinkById = `-- name: GetShortLinkById :one
SELECT
    id,
    original_url,
    short_name,
    short_url,
    created_at
FROM
    short_links
WHERE
    id = $1
`

func (q *Queries) GetShortLinkById(ctx context.Context, id int32) (ShortLink, error) {
	row := q.db.QueryRow(ctx, getShortLinkById, id)
	var i ShortLink
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getShortLinks = `-- name: GetShortLinks :many
SELECT
    id,
    original_url,
    short_name,
    short_url,
    created_at
FROM
    short_links
`

func (q *Queries) GetShortLinks(ctx context.Context) ([]ShortLink, error) {
	rows, err := q.db.Query(ctx, getShortLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShortLink
	for rows.Next() {
		var i ShortLink
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortName,
			&i.ShortUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShortLink = `-- name: UpdateShortLink :one
UPDATE short_links
SET
    original_url = $1,
    short_name = $2,
    short_url = $3
WHERE
    id = $4 RETURNING id,
    original_url,
    short_name,
    short_url,
    created_at
`

type UpdateShortLinkParams struct {
	OriginalUrl string `json:"original_url"`
	ShortName   string `json:"short_name"`
	ShortUrl    string `json:"short_url"`
	ID          int32  `json:"id"`
}

func (q *Queries) UpdateShortLink(ctx context.Context, arg UpdateShortLinkParams) (ShortLink, error) {
	row := q.db.QueryRow(ctx, updateShortLink,
		arg.OriginalUrl,
		arg.ShortName,
		arg.ShortUrl,
		arg.ID,
	)
	var i ShortLink
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}
